# Generated by Django 2.2 on 2023-04-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='data_added',
        ),
    ]
